title: Electronic Engineer
email: jose.carita.077@gmail.com
author: Jose Carita
language: en
logo: /static/img/logo.png
about: Jose Carita
description: > 
  Hi there! This is a site where I can share some description about some interest projects throught my career. The main topics related are Embedded Systems, Signal Processing, Machine Learning and BCI.
baseurl: ""
url: "https://josecarita.github.io"  # the base hostname & protocol
github:  josecarita

allowsearch: false
enableTags:  true

paginate: 10
per_page: 10
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
  math_engine: mathjax

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

social:
  name: Nikolay Falaleev
  links:
    - https://www.linkedin.com/in/jose-carita
    - https://github.com/josecarita
